### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by Mitchell3514** [DTel-HQ/dtel#178]
Need more information, statistics (graphs?).

• General information - every bot has this, what are we doing?
• CS dashboard - information about productivity and stuff
• Economy dashboard - Bus asked for it, then forgot about it, but seems useful

**Comment by SunburntRock89** [comment]
Are we talking Web Dashboard?

**Comment by Rexogamer** [comment]
I *think* so

**Comment by Mitchell3514** [comment]
No, but can do

**Comment by Rexogamer** [comment]
imo web dashboard would be better idea

**Comment by SunburntRock89** [comment]
I'm experienced in that, we should use it to replace the Discord server near enough entirely, it'd be quite a bit more helpful to have access to everything at once
v4 options

**Comment by Rexogamer** [comment]
lol maybe, I guess discord would just be support/611/planning by then

**Comment by SunburntRock89** [comment]
We could even use it for *611 entirely, IE including chat and other stuff like commands. Big red buttons ftw

**Comment by Rexogamer** [comment]
Personally I’d still want to keep 611 to discord, but I’m open for ideas

**Comment by SunburntRock89** [comment]
Who says we have to remove discord entirely?

**Comment by Rexogamer** [comment]
I kinda got that impression from your previous comment but oh well

**Comment by Mitchell3514** [comment]
I don't think we need a complete bot dashboard.
Just some statistics so we know what's up.

**Comment by SunburntRock89** [comment]
it'd be cool tho

**Comment by Rexogamer** [comment]
stats we could track:
- monthly/weekly/daily total calls to *611
- monthly/weekly/daily picked up calls to 611
- monthly/weekly/daily pickups per staff member
- monthly/weekly/daily amount of all calls
- monthly/weekly/daily votes and... >daily usage

**Comment by Mitchell3514** [comment]
A settings dashboard to replace things in Discord would be a no, as it defeats the purpose of the bot.
The same goes for letting users delete their own numbers etc.

Stats would range from
EC: Discoin in/out - Discoin transactions - income/spending - economy size 
611: Picked up calls/staff - Time/call - Calls/time
General: calls/time - commands/time 
And anything we really want

**Comment by SunburntRock89** [comment]
I'm talking only for only CS

**Comment by Mitchell3514** [comment]
That's reasonable

**Comment by Mizzzzo** [comment]
> stats we could track:
> 
> * monthly/weekly/daily total calls to *611
> * monthly/weekly/daily picked up calls to 611
> * monthly/weekly/daily pickups per staff member
> * monthly/weekly/daily amount of all calls
> * monthly/weekly/daily votes and... >daily usage

I like this idea. Could even be a form of way to see what server had the most calls or something and give rewards maybe? Just an idea?

**Comment by Rexogamer** [comment]
@Mizzzzo Maybe, although that would likely be abused (but maybe reward CS who pick up most callers each month or smth)

**Comment by Mizzzzo** [comment]
> @Mizzzzo Maybe, although that would likely be abused (but maybe reward CS who pick up most callers each month or smth)

Yea, that sounds better. I can see it being abused by people. Could give some of the more “inactive” CS a larger incentive to do more maybe?

**Comment by hpenney2** [comment]
Has there been any work on this since it was suggested?

**Comment by Rexogamer** [comment]
@hpenney2 it’s not the biggest priority right now, expect this to be a v4 thing

**Comment by Rexogamer** [comment]
Update: >stats was added (but only for bosses) which shares some basic info; also, should we make it so that we can graph daily/weekly/monthly server growth?

**Comment by Mitchell3514** [comment]
This issue has gone completely off track from where I meant it to be.

My idea was just to create a reminder for myself to have a simple stats command for bosses. 
Well, now we're adding dashboards to v4... closing as it has been accepted.
