### ISSUE TITLE
Promotion channel

### ISSUE THREAD

**Issue by Mitchell3514** [DTel-HQ/dtel#179]
Allow servers to set-up a promotion channel (possibly in the same channel as a number).
This would make promotions also go to those channels.

Benefits:
• This will generate revenue for them, preferably GC (see Fider suggestion)
• `>promotion` will have more value, making it used more.

Linked suggestion:
• Auto-promote

Feedback would be appreciated.

**Comment by Rexogamer** [comment]
I’m kinda against splitting the currency into 2, and I wonder how much this would be used tbh

**Comment by Mitchell3514** [comment]
@Rexogamer can you elaborate on why you're against the currency splitting?

**Comment by Rexogamer** [comment]
Mainly because it’d likely confuse users (I’ve already seen a few people get confused about how it works)

**Comment by Mitchell3514** [comment]
We have made quite a lot of improvements in user knowledge lately.
This has shown to be effective.
So I don't think users would be confused with proper explanation.

Some users are indeed still confused about how numbers are channel-bound.
More explanation on that matter is needed.

**Comment by Rexogamer** [comment]
Sure. We should probably just set out how the different credits work first

**Comment by Mitchell3514** [comment]
Fider has suggestions on this, but a proper plan should be made for v4(?)

**Comment by Mitchell3514** [comment]
Accepted idea in v4.
