### ISSUE TITLE
fix perms

### ISSUE THREAD

**Issue by Mitchell3514** [DTel-HQ/dtel#232]
Mailbox & *411 don't have adequate perm checks. Maybe other commands as well?

**Comment by Rexogamer** [comment]
In v4 we’ll have a better system for perms but ye

**Comment by Mitchell3514** [comment]
Did this get fixed?

**Comment by Rexogamer** [comment]
- Mailbox was fixed in 841978cfd2ac796e4f0b96b1a68a4f381705b762, although you committed the heinous crime of using `message.reply`
- 411 was fixed in 841978cfd2ac796e4f0b96b1a68a4f381705b762

Both of these were on the day of the issue's creation btw

**Comment by Mitchell3514** [comment]
Honestly, we should stop making **everything** embeds. Reply can be nice.

**Comment by turret-dev** [comment]
make call messages embeds now pls

**Comment by Rexogamer** [comment]
`message.channel.send` >>>>>> `message.reply`

it's a grammatical nightmare for one

**Comment by Mitchell3514** [comment]
Nah we have a lot of embeds right now that really should be a reply.

**Comment by Rexogamer** [comment]
No, I'm saying we should just use a plain message because message.reply is just bad, grammatically it's a mess

**Comment by turret-dev** [comment]
message.reply pings the author of the previous messager unless ur in dms for some reason

**Comment by Mitchell3514** [comment]
Reply is nicer than just sending a random message in a lot of cases. And I don't see an issue with grammar, and if there would be an issue then how would it matter anyway?

**Comment by turret-dev** [comment]
the issue would probably be because the reply has your ping followed by a comma and a space prefixed and the comma could introduce gramatical errors and there is no method around this because it is different in dms from actual guilds and there is no clean way to get around this grammar errors

**Comment by Rexogamer** [comment]
closing since this is fixed, continue the reply debate if needed
