### ISSUE TITLE
proper CI/code checking

### ISSUE THREAD

**Issue by Rexogamer** [DTel-HQ/dtel#252]
Currently the only checks we do are CLA and Codebeat on PRs (nothing for direct commits). Since Codebeat doesn't even track branches other than (presumably) the default (and even then it might be outdated, I can't check however), unlinted/tested code can get committed and therefore errors will only be found when we run the new code on the bot. And AFAICT we don't really have tests set up (was this planned for V4?)

**Comment by turret-dev** [comment]
maybe [this?](https://github.com/marketplace/actions/eslint-checker) (first result for "eslint github pull request")
or [this?](https://github.com/marketplace/actions/typescript-compiler) (first result for "github typescript pull request")

**Comment by turret-dev** [comment]
ofc typescript checker for when we get to v4 (or now because it also has a feature to check javascript files)

**Comment by Rexogamer** [comment]
@austinhuang0131 presuming you're the one with access to Better Code Hub (which you turned off on InstaGrabber lol) and Codebeat can you just see what they're actually tracking

**Comment by austinhuang0131** [comment]
BCH is garbage and is only viewable to repo owner, will remove

Codebeat and Codacy (as well as lgtm) just does eslint I think

**Comment by Rexogamer** [comment]
Codebeat doesn't seem to track PRs atm, think you need to set that up manually

**Comment by austinhuang0131** [comment]
codebeat does track PR, [example](https://github.com/austinhuang0131/instagrabber/pull/77)

**Comment by Rexogamer** [comment]
idk if it does on this repo (old PRs just had "this branch is not tracked" and new ones don't have any checks?)

also shouldn't it be checking commits to 3.x too

**Comment by austinhuang0131** [comment]
added Codacy, Codebeat, CodeFactor, Hound & LGTM

removed BCH

for Codacy, someone needs to manually enable patterns; others just use default ones

**Comment by Rexogamer** [comment]
we might want to write some proper tests at some point but this is basically done so
