### ISSUE TITLE
more gambling stuff

### ISSUE THREAD

**Issue by turret-dev** [DTel-HQ/dtel#256]
more money more risk more shit idk
just came up to me

**Comment by turret-dev** [comment]
blackjack and dice roll game maybe?

**Comment by LaNgOStInode** [comment]
blackjack would be fun
idea: mAkE MuLtIPlAyEr gAmBlInG GaMeS
...
please don't get inspiration from that i seriously don't want multiplayer gambling things here. it's a horrible idea ;-;

**Comment by Mitchell3514** [comment]
Has been discussed enough internally to close this.
