### ISSUE TITLE
Change rcall working

### ISSUE THREAD

**Issue by Mitchell3514** [DTel-HQ/dtel#259]
Make `>rcall` connect two numbers using the command instead of dialing a random (most of the time inactive) number.

Different options:
• Create a separate command for this.
• Let `>rcall` dial random numbers, then connect to another rcaller when no call was picked up yet.

**Comment by Rexogamer** [comment]
option 3 sounds best tbh

**Comment by Mitchell3514** [comment]
> option 3 sounds best tbh

Agreed, I like the current system of dialing random numbers. Hybrid is probably best.

**Comment by turret-dev** [comment]
options menu where you can change the mode for rcall

**Comment by haydenwalker980** [comment]
> options menu where you can change the mode for rcall

yeah that sounds cool

**Comment by Peiprjs** [comment]
IDK man that sounds like rcall with extra steps. The thing about RCALL is that there is like a... chance? to get a call

**Comment by LaNgOStInode** [comment]
> options menu where you can change the mode for rcall

yes, it should have all these choices so people can choose what setting they want. That way people who don't understand this [e.g. Peiprjs] can all keep the original mode, while other people can have their creativity and choose new modes

The command should be '>rmode' for Random Mode

**Comment by turret-dev** [comment]
tbh making all of the options for calls and stuff should ne in a menu such as *411 so we're not flooding >help with commands modifying your call experience

**Comment by LaNgOStInode** [comment]
yeah, that makes more sense :P

**Comment by Mitchell3514** [comment]
As it seems right now it will work with a mix of instant-connection and random-dialing.
There have also been more ideas sent to me in DMs which we will look at.
