### ISSUE TITLE
Add menu/catalog feature you can enable to sell things/ food over the phone

### ISSUE THREAD

**Issue by d86592** [DTel-HQ/dtel#272]
You would be able to run a cmd to see it and send another cmd to buy the item and people can add stuff in for instant delivery if they wanted.

**Comment by LaNgOStInode** [comment]
this is an amazing idea, this way the McDonalds food channel can be more realistic

**Comment by Mitchell3514** [comment]
I can remember this passing by in a conversation a long time ago. I've also had it on a list somewhere... wonder where that went.
Anyway, it's noted in a safe place now. Thanks!

**Comment by Mitchell3514** [comment]
This exact idea might surpass the v4 release to wait for the new bot option menu, but the backbone will already be there for another feature.
