### ISSUE TITLE
Do a command for add numbers to a contact list.

### ISSUE THREAD

**Issue by prozinho2009** [DTel-HQ/dtel#292]
Make a contact list so you can add the number of people and add the contact so you don't forget.

The prefix Can be >createcontact and when you write it pop up an embeded message saying which number you want to add to the contact list and when you put another iembededmessage will appear saying which number you want to add to the contact and if all are corrected contact successfully added appears.

And you can see it using >contacts and you can delete using >deletecontact and select the contact.

**Comment by turret-dev** [comment]
this command already exists.
